flowchart TD
    User[User/Client] -->|API Request| API[FastAPI App]
    
    API -->|/kubernetes/*| KP[Kubernetes Proxy]
    API -->|/argo/cd/*| AP[Argo CD Proxy]
    API -->|/tvp/*| TVP[TVP]
        
    TVP -->|Status| TS[TVP Status]
    TVP -->|Reconcile| R[Reconciliation]
    
    TS --> Git[Git Repository]
    R --> Git
    R --> KA
    KP -->|Auth token| KA[Kubernetes API Server]
    AP -->|Auth token| AA[Argo CD API]
    subgraph "Kubernetes Cluster"
        KA --> Kubernetes[(Kubernetes Microservices)]
        AA --> ArgoCD[(Argo CD Service)]
        AA -->|Login| Auth[Argo CD Auth]
    end
    Auth -->|Response| AP
    Auth -->|Response| KP

    classDef user fill:#bbf,stroke:#33f,stroke-width:2px
    classDef app fill:#f9f,stroke:#333,stroke-width:2px
    classDef external fill:#bfb,stroke:#3f3,stroke-width:2px
    
    class User user
    class API,KP,AP,TVP,TS,R app
    class Kubernetes,ArgoCD,Git,KA,AA,Auth external
