sequenceDiagram
    participant Client
    participant FastAPI
    participant Kubernetes as Kubernetes Cluster
    participant ArgoCD as Argo CD
    
    Client->>FastAPI: GET /health
    
    FastAPI->>Kubernetes: list_namespace()
    alt Kubernetes Healthy
        Kubernetes-->>FastAPI: Success response
        FastAPI->>FastAPI: Kubernetes status = "healthy"
    else Kubernetes Unhealthy
        Kubernetes-->>FastAPI: Error
        FastAPI->>FastAPI: Kubernetes status = "unhealthy"
        FastAPI->>FastAPI: Overall status = "degraded"
    end
    
    FastAPI->>ArgoCD: get_argo_cd_token()
    alt ArgoCD Healthy
        ArgoCD-->>FastAPI: Valid token
        FastAPI->>FastAPI: Argo CD status = "healthy"
    else ArgoCD Unhealthy
        ArgoCD-->>FastAPI: Error
        FastAPI->>FastAPI: Argo  CD status = "unhealthy"
        FastAPI->>FastAPI: Overall status = "degraded"
    end
    
    FastAPI-->>Client: Health status response
