flowchart TD
    main[main.py] --> tvp[tvp.py]
    main --> kubernetes[kubernetes_api.py]
    main --> argo[argo_cd_api.py]
    main --> config[config.py]
    
    tvp --> git[git commands]
    tvp --> config
    tvp --> kubernetes_api[(Kubernetes API)]
    
    kubernetes --> config
    kubernetes --> kubernetes_api
    
    argo --> config
    argo --> argo_cd_api[(Argo CD API)]
    
    config --> kubernetes_client[Kubernetes Client Library]
    config --> env[Environment Variables]
    
    client[Client Applications] --> main
    
    classDef appModule fill:#bef,stroke:#333,stroke-width:2px
    classDef externalSys fill:#f96,stroke:#333,stroke-width:2px
    classDef config fill:#9e9,stroke:#333,stroke-width:2px
    classDef client fill:#f8d,stroke:#333,stroke-width:2px
    
    class main,tvp,kubernetes,argo appModule
    class kubernetes_api,argo_cd_api,git externalSys
    class config,kubernetes_client,env config
    class client client
